# Compiler Configuration
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
android.builtInKotlin=false
android.newDsl=false
kotlin.code.style=official
# Project Configuration
project.name=Bilibili_Innocent_Lab
project.android.compileSdk=37
project.android.minSdk=27
project.android.targetSdk=35
project.app.packageName=Bilibili_Innocent_Lab.pro
project.app.versionName="1.0.6"
project.app.versionCode=7
