package com.Bilibili_Innocent_Lab.xposedmodule.hook.feature

/** 新增功能的稳定配置键；旧功能键在完成迁移前仍保留在 HookEntry。 */
internal object FeaturePreferences {
    const val HIDE_VIDEO_DETAIL_APP_PROMOTION = "hide_video_detail_app_promotion"
    const val HIDE_HOME_GAME_MENU = "hide_home_game_menu"
    const val HIDE_HOME_SEARCH_DEFAULT_WORD = "hide_home_search_default_word"
    const val HOME_VERTICAL_OPEN_DETAIL = "home_vertical_open_detail"
    const val REMOVE_HOME_RECOMMEND_ADS = "remove_home_recommend_ads"
    const val REMOVE_HOME_RECOMMEND_PICTURES = "remove_home_recommend_pictures"
    const val REMOVE_HOME_RECOMMEND_GAME_PROMOTIONS = "remove_home_recommend_game_promotions"
    const val HOME_RECOMMEND_TITLE_FILTER_ENABLED = "home_recommend_title_filter_enabled"
    const val HOME_RECOMMEND_TITLE_FILTER_KEYWORDS = "home_recommend_title_filter_keywords"
    const val REMOVE_HOME_RECOMMEND_LIVE = "remove_home_recommend_live"
    const val REMOVE_HOME_RECOMMEND_COURSES = "remove_home_recommend_courses"
    const val REMOVE_HOME_RECOMMEND_VERTICAL = "remove_home_recommend_vertical"
    const val REMOVE_HOME_RECOMMEND_LARGE = "remove_home_recommend_large"
    const val HOME_TAB_HIDDEN_RULES = "home_tab_hidden_rules"
    const val HOME_COMPONENT_HIDDEN_RULES = "home_component_hidden_rules"
    const val RECOMMEND_VIDEO_MIN_DURATION_SECONDS = "recommend_video_min_duration_seconds"
    const val RECOMMEND_VIDEO_MAX_DURATION_SECONDS = "recommend_video_max_duration_seconds"
    const val HIDE_MINE_VIP = "hide_mine_vip"
    const val KEEP_MINE_VIP_SPACE = "keep_mine_vip_space"
    const val BLOCK_APP_UPDATE = "block_app_update"
    const val HIDE_DYNAMIC_CITY_TAB = "hide_dynamic_city_tab"
    const val HIDE_DYNAMIC_SCHOOL_TAB = "hide_dynamic_school_tab"
    const val PREFER_DYNAMIC_VIDEO_TAB = "prefer_dynamic_video_tab"
    const val SHOW_FULL_NUMBERS = "show_full_numbers"
    const val HIDE_PLAYER_PORTRAIT_CONTROL = "hide_player_portrait_control"
    const val HIDE_PLAYER_INTERACTIVE_OVERLAYS = "hide_player_interactive_overlays"
    const val TRANSPARENT_PLAYER_STATUS_BAR = "transparent_player_status_bar"
    const val REMOVE_RELATE_COMMERCIAL = "remove_relate_commercial"
    const val REMOVE_RELATE_GAME = "remove_relate_game"
    const val REMOVE_RELATE_LIVE = "remove_relate_live"
    const val REMOVE_RELATE_COURSE = "remove_relate_course"
    const val REMOVE_RELATE_SPECIAL = "remove_relate_special"
    const val VIDEO_RELATE_MATCHING_ENHANCEMENT_ENABLED =
        "video_relate_matching_enhancement_enabled"
    const val VIDEO_RELATE_STRONG_MODE_ENABLED = "video_relate_strong_mode_enabled"
    const val VIDEO_RELATE_REASON_FILTER_ENABLED = "video_relate_reason_filter_enabled"
    const val VIDEO_RELATE_REASON_FILTER_KEYWORDS = "video_relate_reason_filter_keywords"
    const val MINE_COMPONENT_HIDDEN_RULES = "mine_component_hidden_rules"
    /** “我的”页勾选隐藏的组件 id 集合（新 UI 勾选列表持久化，换行/逗号分隔的字符串）。 */
    const val MINE_COMPONENT_HIDDEN_IDS = "mine_component_hidden_ids"
    /** 新版勾选项的稳定选择键 JSON 数组；旧 id/标题规则继续作为兼容输入保留。 */
    const val MINE_COMPONENT_HIDDEN_SELECTORS = "mine_component_hidden_selectors"
    /** 宿主剪枝时写入的可屏蔽项快照 JSON（模块 UI 勾选列表数据源；仅宿主写、模块 App 读）。 */
    const val MINE_COMPONENT_SCAN_SNAPSHOT = "mine_component_scan_snapshot"
    const val REMOVE_STORY_ADS = "remove_story_ads"
    const val REMOVE_STORY_LIVE = "remove_story_live"
    const val REMOVE_STORY_GAMES = "remove_story_games"
    const val REMOVE_STORY_BANGUMI = "remove_story_bangumi"
    const val REMOVE_STORY_COURSES = "remove_story_courses"
    const val REMOVE_STORY_SHORT_DRAMA = "remove_story_short_drama"
    const val REMOVE_STORY_SHOPPING = "remove_story_shopping"
    const val REMOVE_STORY_MOVIES = "remove_story_movies"
    const val REMOVE_STORY_DOCUMENTARIES = "remove_story_documentaries"
    const val REMOVE_STORY_TV = "remove_story_tv"
    const val REMOVE_STORY_VARIETY = "remove_story_variety"
    const val REMOVE_STORY_MUSIC = "remove_story_music"
    const val BOTTOM_BAR_HIDDEN_RULES = "bottom_bar_hidden_rules"
    const val PLAYER_DEFAULT_QUALITY_QN = "player_default_quality_qn"
    const val BLOCK_TEENAGERS_MODE_PROMPT = "block_teenagers_mode_prompt"
    const val REMOVE_COMMENT_SEARCH_LINKS = "remove_comment_search_links"
    const val REMOVE_COMMENT_EMPTY_GUIDE = "remove_comment_empty_guide"
    const val REMOVE_COMMENT_VOTE_WIDGETS = "remove_comment_vote_widgets"
    const val REMOVE_COMMENT_FOLLOW_BUTTONS = "remove_comment_follow_buttons"
    const val REMOVE_COMMENT_QOE = "remove_comment_qoe"
    const val REMOVE_COMMENT_OPERATIONS = "remove_comment_operations"
    const val BLOCK_COMMENT_QUICK_REPLY = "block_comment_quick_reply"
    const val HIDE_COMMENT_SECTION = "hide_comment_section"
    const val REPLY_TOPOLOGY_ENABLED = "reply_topology_enabled"
    const val COMMENT_KEYWORD_FILTER_ENABLED = "comment_keyword_filter_enabled"
    const val COMMENT_FILTER_KEYWORDS = "comment_filter_keywords"
    const val COMMENT_MIN_LEVEL_FILTER_ENABLED = "comment_min_level_filter_enabled"
    const val COMMENT_MIN_LEVEL = "comment_min_level"
    const val PURIFY_SPLASH_ADS = "purify_splash_ads"
}
